controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper
initial:  # Define initial robot poses per group
  - group: arm
    pose: arm_home
  - group: gripper
    pose: opened_gripper