arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
    - joint_a7
  gains:
    joint_a1:
      p: 1000
      d: 1.2
      i: 0
      i_clamp: 100
    joint_a2:
      p: 1000
      d: 1.2
      i: 0
      i_clamp: 100
    joint_a3:
      p: 1000
      d: 1.2
      i: 0
      i_clamp: 100
    joint_a4:
      p: 1000
      d: 1.2
      i: 0
      i_clamp: 100
    joint_a5:
      p: 1000
      d: 1.2
      i: 0
      i_clamp: 100
    joint_a6:
      p: 1000
      d: 1.2
      i: 0
      i_clamp: 100
    joint_a7:
      p: 1000
      d: 1.2
      i: 0
      i_clamp: 100
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper
  gains:
    gripper:
      p: 1000
      d: 0.8
      i: 0
      i_clamp: 100
