# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
    - joint_a7
    - gripper
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
    - joint_a7
  gains:
    joint_a1:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
    joint_a2:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
    joint_a3:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
    joint_a4:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
    joint_a5:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
    joint_a6:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
    joint_a7:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
  constraints:
    goal_time: 2.0
  state_publish_rate: 50

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper
  gains:
    gripper:
      p: 1000
      d: 0
      i: 0
      i_clamp: 0
  state_publish_rate: 50

controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper
