#kuka_lbr_iiwa:

#  gazebo_ros_control:
#    type: effort_controllers/JointPositionController
#    joints:
#      - joint_a1
#      - joint_a2
#      - joint_a3
#      - joint_a4
#      - joint_a5
#      - joint_a6
#      - joint_a7
#    pid_gains:
#      joint_a1:
#        p: 100.0
#        i: 0.01 
#        d: 10.0
#      joint_a2:
#        p: 100.0
#        i: 0.01 
#        d: 10.0
#      joint_a3:
#        p: 100.0
#        i: 0.01 
#        d: 10.0
#      joint_a4:
#        p: 100.0
#        i: 0.01 
#        d: 10.0
#      joint_a5:
#        p: 100.0
#        i: 0.01 
#        d: 10.0
#      joint_a6:
#        p: 100.0
#        i: 0.01 
#        d: 10.0
#      joint_a7:
#        p: 100.0
#        i: 0.01 
#        d: 10.0

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a1
  pid: {p: 1000.0, i: 0.0, d: 0.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a2
  pid: {p: 1000.0, i: 0.0, d: 0.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a3
  pid: {p: 1000.0, i: 0.0, d: 0.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a4
  pid: {p: 1000.0, i: 0.0, d: 0.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a5
  pid: {p: 1000.0, i: 0.0, d: 0.0}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a6
  pid: {p: 1000.0, i: 0.0, d: 0.0}
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_a7
  pid: {p: 1000.0, i: 0.0, d: 0.0}
joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper
  pid: {p: 1000.0, i: 0.0, d: 0.0}
